//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кафедра
    {
        public int IdКафедра { get; set; }
        public string Название { get; set; }
        public string Телефон { get; set; }
        public int IdФакультет { get; set; }
        public int IdЗавКаф { get; set; }
    
        public virtual ЗавКафедрой ЗавКафедрой { get; set; }
        public virtual Факультет Факультет { get; set; }
    }
}
