//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class УчебныйПлан
    {
        public int IdПлан { get; set; }
        public int IdДисцип { get; set; }
        public int IdСпец { get; set; }
        public int ЧасыЛекции { get; set; }
        public int ЧасыЛабРабот { get; set; }
        public int ЧасыПракРабот { get; set; }
        public int ЧасыКурсового { get; set; }
        public int IdВидОтчет { get; set; }
        public int Семестр { get; set; }
    
        public virtual ВидОтчетности ВидОтчетности { get; set; }
        public virtual Дисциплина Дисциплина { get; set; }
        public virtual Специальность Специальность { get; set; }
    }
}
