//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstituteEntities : DbContext
    {
        public InstituteEntities()
            : base("name=InstituteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ВидОтчетности> ВидОтчетности { get; set; }
        public virtual DbSet<Дисциплина> Дисциплина { get; set; }
        public virtual DbSet<ЗавКафедрой> ЗавКафедрой { get; set; }
        public virtual DbSet<Звание> Звание { get; set; }
        public virtual DbSet<Кафедра> Кафедра { get; set; }
        public virtual DbSet<Квалификация> Квалификация { get; set; }
        public virtual DbSet<Специальность> Специальность { get; set; }
        public virtual DbSet<Степень> Степень { get; set; }
        public virtual DbSet<УчебныйПлан> УчебныйПлан { get; set; }
        public virtual DbSet<Факультет> Факультет { get; set; }
        public virtual DbSet<ФормаОбучения> ФормаОбучения { get; set; }
    }
}
