//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗавКафедрой
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЗавКафедрой()
        {
            this.Кафедра = new HashSet<Кафедра>();
        }
    
        public int IdЗавКаф { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int IdСтепень { get; set; }
        public int IdЗвание { get; set; }
    
        public virtual Звание Звание { get; set; }
        public virtual Степень Степень { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Кафедра> Кафедра { get; set; }
    }
}
