//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute
{
    using System;
    using System.Collections.Generic;
    
    public partial class Специальность
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Специальность()
        {
            this.УчебныйПлан = new HashSet<УчебныйПлан>();
        }
    
        public int IdСпец { get; set; }
        public string Название { get; set; }
        public int IdКвалиф { get; set; }
        public string Продолжительность { get; set; }
        public int IdФормаОбуч { get; set; }
        public int IdФакультет { get; set; }
    
        public virtual Квалификация Квалификация { get; set; }
        public virtual Факультет Факультет { get; set; }
        public virtual ФормаОбучения ФормаОбучения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УчебныйПлан> УчебныйПлан { get; set; }
    }
}
